global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['192.168.0.173:9099']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

